animations {
    enabled = true

  # Default curves
    #        NAME,           X0,   Y0,    X1,   Y1
    bezier = easeOutQuint,   0.23, 1,     0.32, 1
    bezier = easeInOut,      0.65, 0.05,  0.36, 1
    bezier = linear,         0,    0,     1,    1
    bezier = almostLinear,   0.5,  0.5,   0.75, 1
    bezier = quick,          0.15, 0,     0.1,  1

  # Animations
    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = global,        1,     10,    easeInOut
    animation = border,        1,     2,     easeInOut

    animation = windows,       1,     2,     easeInOut,    popin 90%
    animation = windowsIn,     1,     2,     easeInOut,    popin 90%
    animation = windowsOut,    1,     2,     easeInOut,    popin 90%
    animation = windowsMove,   1,     2,     easeInOut,    popin 90%

    animation = fade,          1,     2,     easeInOut
    animation = fadeIn,        1,     2,     easeInOut
    animation = fadeOut,       1,     2,     easeInOut
    animation = fadeSwitch,    1,     2,     easeInOut
    animation = fadeShadow,    1,     2,     easeInOut
    animation = fadeDim,       1,     2,     easeInOut
    animation = fadeDpms,      1,     2,     easeInOut
    animation = fadeLayersIn,  1,     2,     easeInOut
    animation = fadeLayersOut, 1,     2,     easeInOut

    animation = layers,        1,     2,     easeInOut,    slide
    animation = layersIn,      1,     2,     easeInOut,    slide
    animation = layersOut,     1,     2,     easeInOut,    slide

    animation = workspaces,    1,     2,     easeInOut,    fade
    animation = workspacesIn,  1,     2,     easeInOut,    fade
    animation = workspacesOut, 1,     2,     easeInOut,    fade

    animation = zoomFactor,    1,     2,     easeInOut
}
