# Ignore maximize requests
windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*
}

# Make file picker windows floating
windowrule {
  name = windowrule-2
  float = on
  center = on
  border_size = 0
  match:class = (xdg-desktop-portal-gtk)
}

windowrule {
  name = windowrule-3
  float = on
  center = on
  match:class = (xdg-desktop-portal-hyprland)
}

# Make screenshot windows floating
windowrule {
  name = satty-overlay
  float = on
  center = on
  match:class = ^(com.gabm.satty)$
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Noctalia blur
layerrule {
    name = noctalia-shell-blur

    match:namespace = noctalia-bar-content-eDP-1

    blur = on

    ignore_alpha = 0.5
}
